apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-demo-httpd
  namespace: f5demo-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: f5-demo-httpd
  template:
    metadata:
      labels:
        app: f5-demo-httpd
    spec:
      containers:
      - name: f5-demo-httpd
        image: f5devcentral/f5-demo-httpd:nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80