apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: f5demo
  namespace: f5demo-ns
spec:
  host: vsdemof5.example.com
  upstreams:
  - name: demo
    service: demo-service-clusterip
    port: 80
    lb-method: least_conn
  routes:
  - path: /
    action:
      pass: demo
#    errorPages:
#    - codes: [404]
#      return:
#        code: 200
#        body: "Original resource not found, but success!"
  - path: /nginx
    action:
      redirect:
        code: 301 
        url: https://www.nginx.com        
  - path: /hello
    route: vsroute-ns/demovirtualserverroute
