apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: f5demo
spec:
  host: vsdemof5.example.com
  upstreams:
  - name: demo
    service: demo-service-clusterip
    port: 80
  routes:
  - path: /
    action:
      pass: demo
  - path: /nginx
    action:
      return:
        code: 301
        url: https://www.nginx.com
  - path: /hello
    route: demovirtualserverroute