#cloud-config
package_upgrade: true
packages:
  - snap
  - docker
runcmd:
  - sudo snap install microk8s --classic --channel 1.18/stable
  - sudo usermod -a -G microk8s ${username}
  - sudo chown -f -R ${username} ~/.kube
  - microk8s status --wait-ready
  - microk8s enable dns
  - sudo chmod 766 /etc/bash.bashrc
  - sudo echo "alias kubectl='microk8s kubectl'" >> /etc/bash.bashrc