#cloud-config
package_upgrade: true
packages:
  - docker.io
  - make
snap:
  commands:
#    - snap install helm --classic
    - snap install microk8s --classic --channel 1.19/stable
runcmd:
  - sudo usermod -a -G microk8s ${username}
  - sudo usermod -aG docker ${username}
  - sudo chown -f -R ${username} /home/${username}/.kube
  - microk8s status --wait-ready
  - microk8s enable dns
  - microk8s enable helm3
  - microk8s enable registry
  - microk8s enable metrics-server
  - sudo chmod 766 /etc/bash.bashrc
  - sudo echo "alias kubectl='microk8s kubectl'" >> /etc/bash.bashrc
  - sudo echo "alias helm='microk8s helm3'" >> /etc/bash.bashrc
  - git -C /home/${username}/ clone https://github.com/projectcalico/calico.git
  - sudo chown -R ${username} /home/${username}/calico
  - git -C /home/${username}/ clone https://github.com/nginxinc/kubernetes-ingress/
  - sudo chown -R ${username} /home/${username}/kubernetes-ingress
  - git -C /home/${username}/ clone https://github.com/Gyllenhammar/TF-Azure-KIC-CIS.git
  - sudo chown -R ${username} /home/${username}/TF-Azure-KIC-CIS
