#cloud-config
package_upgrade: true
packages:
  - docker.io
  - make
snap:
  commands:
#    - snap install helm --classic
    - snap install microk8s --classic --channel 1.18/stable
runcmd:
  - sudo usermod -a -G microk8s ${username}
  - sudo usermod -aG docker ${username}
  - sudo chown -f -R ${username} ~/.kube
  - microk8s status --wait-ready
  - microk8s enable dns
  - microk8s enable helm3
  - microk8s enable registry
  - sudo chmod 766 /etc/bash.bashrc
  - sudo echo "alias kubectl='microk8s kubectl'" >> /etc/bash.bashrc
  - sudo echo "alias helm='microk8s helm3'" >> /etc/bash.bashrc